public class EvenFibonacciNumbers {

    /* PROBLEM:
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
     * By starting with 1 and 2 the first 10 terms will be:
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     * By considering the terms in the Fibonacci sequence whose values do not exceed four million
     * find the sum of the even-valued terms.
     */

    public static void main(String[] args) {
        final int LIMIT = 4_000_000;

        int a = 1; 
        int b = 2;  
        int sumEven = 0;

        while (b <= LIMIT) {
            if ((b & 1) == 0)
            { 
                sumEven += b;
            }
            int next = a + b;
            a = b;
            b = next;
        }

        System.out.println(sumEven);
    }
}
